language: minimal
services:
- docker
script:
- docker run -v "$TRAVIS_BUILD_DIR":/postfacto postfacto/dev:2.6.3-12.6.0 /bin/bash -c "cd /postfacto && npm config set user 0 && npm config set unsafe-perm true && ./deps.sh && EPHEMERAL_CONTAINER=true ./test.sh && ./package.sh"
deploy:
  provider: releases
  draft: true
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
  api_key:
    secure: BYSC5meSt0D85xPS7DuousoIs8sB/Pm2BEvFFU1qBwCzFDVRITsZ/Uf6lL3KAh51g/6f1D1T1mi/RQvwLTDeDcCgIT2maOeWNmvyK9FGBkyt99sROcsouaJ8avfKUwmAlPcdA4kba6Le95Y2Rok5DUdTw7DROnInsKIdL2QRTspbwrtiSrerkeSxz/NkKtV5ztMXNP7YSQtineqCGP7jpnpsvb0CMEUI5dCaYHY0NsX38rB3ks4wdKopWE8E4sMC2yvw6jHfiWLdJPZa/tnmTVXDtbH6f9CuBONdXqk2gsS0gxvw3So6IegnYQWN09urck1HDkFoxSFwIHF54FJGt8hGpodhQXrYVP6tLtk5/TtdEl6Ezw0yxYtO99k7vaG9eouLmBRKJH0ZoBk0Dc/JPFd0yPI5YuxpAhNmBxXi+ZHNIbjVo30F7gncXIypvCd5dxGRRz9V8LnuJifeESVMnXbhK1sxtuzcjhqoR6lLEIqkKUodgV5+QgP/yYT2gJKKRkyBS0lITS4nokcDLpCLzgjfAdcNYxiNnkf6UGNLfyiPxwSOC8kT4/b72d+0GU8aHilp3dZVm/VnMwbCVDmldmVc8DvrgfdKUXfT+SbuFHVmaY38ZQij+VsY7YY3pUH+H6RrY+Pi68uRKk2pPKM2VNe2L/69zAvTL3xG5KmGWNI=
  file: package.zip
