---
applications:
- name: ((api-app-name))
  instances: 2
  buildpack: https://github.com/cloudfoundry/ruby-buildpack.git#v1.7.40
  memory: 256M
  command: bundle exec rake db:migrate && bundle exec rails s -p $PORT -e $RAILS_ENV
  services:
    - postfacto-db
    - postfacto-redis
  env:
    CLIENT_ORIGIN: https://((web-app-name)).((pcf-url))
    WEBSOCKET_PORT: 4443
    SESSION_TIME: ((session-time))
